<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="22" hostname="DESKTOP-PO3T4V3" failures="34" tests="47" name="API Integration Automation Test" time="43.529" errors="0" timestamp="2022-10-31T09:58:54 AMT">
  <testcase classname="testCases.IqSoft_API_2_Authorization_Positive_Test" name="AuthorizationAPIValidateStatusCod" time="0.04"/>
  <testcase classname="testCases.IqSoft_API_2_Authorization_Positive_Test" name="AuthorizationAPIValidatePositiveResponse" time="0.006"/>
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Positive_Test" name="GetBalanceAPIValidateStatusCod" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Positive_Test" name="GetBalanceAPIValidatePositiveResponse" time="0.004"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Positive_Test" name="CreditAPIValidateStatusCod" time="0.003"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Positive_Test" name="CreditAPIValidatePositiveResponse" time="0.008">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Description:  expected [null] but found []">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Description:  expected [null] but found []
at testCases.IqSoft_API_4_Credit_Positive_Test.CreditAPIValidatePositiveResponse(IqSoft_API_4_Credit_Positive_Test.java:110)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidatePositiveResponse -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Positive_Test" name="DebitAPIValidateStatusCod" time="0.003"/>
  <testcase classname="testCases.IqSoft_API_5_Debit_Positive_Test" name="DebitAPIValidatePositiveResponse" time="0.004">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Description:  expected [null] but found []">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Description:  expected [null] but found []
at testCases.IqSoft_API_5_Debit_Positive_Test.DebitAPIValidatePositiveResponse(IqSoft_API_5_Debit_Positive_Test.java:121)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidatePositiveResponse -->
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" name="RollBackAPIValidateStatusCod" time="0.001"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" name="RollBackAPIValidatePositiveResponse" time="0.003">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [0] but found [21],
	Description: RollbackTransactionId Not Found expected [null] but found [RollbackTransactionId Not Found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [0] but found [21],
Description: RollbackTransactionId Not Found expected [null] but found [RollbackTransactionId Not Found]
at testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test.RollBackAPIValidatePositiveResponse(IqSoft_API_6_RollBackCreditWithDebit_Positive_Test.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidatePositiveResponse -->
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" name="RollBackAPIValidatePositiveResponseBalanceCorrection" time="0.002">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	afterRollBackCredit: 58.1 = beforeAll: 54.1 expected [54.1] but found [58.1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
afterRollBackCredit: 58.1 = beforeAll: 54.1 expected [54.1] but found [58.1]
at testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test.RollBackAPIValidatePositiveResponseBalanceCorrection(IqSoft_API_6_RollBackCreditWithDebit_Positive_Test.java:106)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidatePositiveResponseBalanceCorrection -->
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" name="RollBackAPIValidateStatusCod" time="0.002"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" name="RollBackAPIValidatePositiveResponse" time="0.002">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [0] but found [21],
	Description: RollbackTransactionId Not Found expected [null] but found [RollbackTransactionId Not Found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [0] but found [21],
Description: RollbackTransactionId Not Found expected [null] but found [RollbackTransactionId Not Found]
at testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test.RollBackAPIValidatePositiveResponse(IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidatePositiveResponse -->
  <testcase classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" name="RollBackAPIValidatePositiveResponseBalanceCorrection" time="0.001">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	afterRollBackCredit: 57.1 = beforeAll: 58.1 expected [58.1] but found [57.1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
afterRollBackCredit: 57.1 = beforeAll: 58.1 expected [58.1] but found [57.1]
at testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test.RollBackAPIValidatePositiveResponseBalanceCorrection(IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test.java:94)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidatePositiveResponseBalanceCorrection -->
  <testcase classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" name="RollBackAPIValidateStatusCod" time="0.003"/>
  <testcase classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" name="RollBackAPIValidatePositiveResponse" time="0.003">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [0] but found [21],
	Description: RollbackTransactionId Not Found expected [null] but found [RollbackTransactionId Not Found]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [0] but found [21],
Description: RollbackTransactionId Not Found expected [null] but found [RollbackTransactionId Not Found]
at testCases.IqSoft_API_6_RollBackDebit_Positive_Test.RollBackAPIValidatePositiveResponse(IqSoft_API_6_RollBackDebit_Positive_Test.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidatePositiveResponse -->
  <testcase classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" name="RollBackAPIValidatePositiveResponseBalanceCorrection" time="0.002">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	afterRollBackDebit: 61.1 = afterCredit: 56.1 expected [56.1] but found [61.1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
afterRollBackDebit: 61.1 = afterCredit: 56.1 expected [56.1] but found [61.1]
at testCases.IqSoft_API_6_RollBackDebit_Positive_Test.RollBackAPIValidatePositiveResponseBalanceCorrection(IqSoft_API_6_RollBackDebit_Positive_Test.java:106)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidatePositiveResponseBalanceCorrection -->
  <testcase classname="testCases.IqSoft_API_2_Authorization_Negative_Test" name="AuthorizationAPIValidateResponseWithExpiredToken" time="0.28">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null]
at testCases.IqSoft_API_2_Authorization_Negative_Test.AuthorizationAPIValidateResponseWithExpiredToken(IqSoft_API_2_Authorization_Negative_Test.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- AuthorizationAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_2_Authorization_Negative_Test" name="AuthorizationAPIValidateResponseWithInvalidToken" time="0.271">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [22] but found [0],
	Error Description: null expected [ClientNotFound] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [22] but found [0],
Error Description: null expected [ClientNotFound] but found [null]
at testCases.IqSoft_API_2_Authorization_Negative_Test.AuthorizationAPIValidateResponseWithInvalidToken(IqSoft_API_2_Authorization_Negative_Test.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- AuthorizationAPIValidateResponseWithInvalidToken -->
  <testcase classname="testCases.IqSoft_API_2_Authorization_Negative_Test" name="AuthorizationAPIValidateResponseWithInvalidProductID" time="0.285">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [43] but found [0],
	Error Description: null expected [ProductNotFound] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [43] but found [0],
Error Description: null expected [ProductNotFound] but found [null]
at testCases.IqSoft_API_2_Authorization_Negative_Test.AuthorizationAPIValidateResponseWithInvalidProductID(IqSoft_API_2_Authorization_Negative_Test.java:96)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- AuthorizationAPIValidateResponseWithInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithExpiredToken" time="0.356">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description: null expected [SessionExpired] but found [null]
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithExpiredToken(IqSoft_API_3_GetBalance_Negative_Test.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- GetBalanceAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithInvalidToken" time="0.357">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [22] but found [0],
	Error Description: null expected [error login] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [22] but found [0],
Error Description: null expected [error login] but found [null]
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithInvalidToken(IqSoft_API_3_GetBalance_Negative_Test.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- GetBalanceAPIValidateResponseWithInvalidToken -->
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithInvalidCurrencyID" time="0.27">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [20] but found [0],
	Error Description: null expected [CurrencyNotExists] but found [null]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [20] but found [0],
Error Description: null expected [CurrencyNotExists] but found [null]
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithInvalidCurrencyID(IqSoft_API_3_GetBalance_Negative_Test.java:89)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- GetBalanceAPIValidateResponseWithInvalidCurrencyID -->
  <testcase classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" name="GetBalanceAPIValidateResponseWithOtherCurrencyID" time="0.559">
    <failure type="java.lang.AssertionError" message="balanceUSD VS balanceEUR did not expect [61.1] but found [61.1]">
      <![CDATA[java.lang.AssertionError: balanceUSD VS balanceEUR did not expect [61.1] but found [61.1]
at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithOtherCurrencyID(IqSoft_API_3_GetBalance_Negative_Test.java:113)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- GetBalanceAPIValidateResponseWithOtherCurrencyID -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithExpiredToken" time="0.927">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [29] but found [0],
	Error Description:  expected [SessionExpired] but found [],
	amountBeforeCredit = amountAfterCredit: 61.1 = 60.1 expected [60.1] but found [61.1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [29] but found [0],
Error Description:  expected [SessionExpired] but found [],
amountBeforeCredit = amountAfterCredit: 61.1 = 60.1 expected [60.1] but found [61.1]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithExpiredToken(IqSoft_API_4_Credit_Negative_Test.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithExpiredToken -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidToken" time="0.824">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [22] but found [0],
	Error Description:  expected [error login] but found [],
	expected [59.1] but found [60.1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [22] but found [0],
Error Description:  expected [error login] but found [],
expected [59.1] but found [60.1]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidToken(IqSoft_API_4_Credit_Negative_Test.java:101)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithInvalidToken -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidProductID" time="0.812">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [43] but found [0],
	Error Description:  expected [game not available] but found [],
	Amount BeforeCredit: 59.1Amount AfterCredit: 58.1 expected [58.1] but found [59.1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [43] but found [0],
Error Description:  expected [game not available] but found [],
Amount BeforeCredit: 59.1Amount AfterCredit: 58.1 expected [58.1] but found [59.1]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidProductID(IqSoft_API_4_Credit_Negative_Test.java:143)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseUsingTransactionIDTwice" time="1.386"/>
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseUsingAmountHigherThenBalance" time="0.834">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [63] but found [21],
	Error Description: Insufficient funds expected [balance less then bet Amount] but found [Insufficient funds]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [63] but found [21],
Error Description: Insufficient funds expected [balance less then bet Amount] but found [Insufficient funds]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseUsingAmountHigherThenBalance(IqSoft_API_4_Credit_Negative_Test.java:236)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseUsingAmountHigherThenBalance -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.801">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [39] but found [21],
	Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [39] but found [21],
Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount(IqSoft_API_4_Credit_Negative_Test.java:280)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.848">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [39] but found [21],
	Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
	AmountBeforeCredit: 57.1 = amountAfterCredit : 58.1 expected [58.1] but found [57.1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [39] but found [21],
Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
AmountBeforeCredit: 57.1 = amountAfterCredit : 58.1 expected [58.1] but found [57.1]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount(IqSoft_API_4_Credit_Negative_Test.java:280)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.829">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [39] but found [21],
	Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
	AmountBeforeCredit: 58.1 = amountAfterCredit : 59.6 expected [59.6] but found [58.1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [39] but found [21],
Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
AmountBeforeCredit: 58.1 = amountAfterCredit : 59.6 expected [59.6] but found [58.1]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount(IqSoft_API_4_Credit_Negative_Test.java:280)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.895">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [39] but found [21],
	Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
	AmountBeforeCredit: 59.6 = amountAfterCredit : 60.65 expected [60.65] but found [59.6]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [39] but found [21],
Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
AmountBeforeCredit: 59.6 = amountAfterCredit : 60.65 expected [60.65] but found [59.6]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount(IqSoft_API_4_Credit_Negative_Test.java:280)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_4_Credit_Negative_Test" name="CreditAPIValidateResponseWithInvalidAmount" time="0.796">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [39] but found [21],
	Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
	AmountBeforeCredit: 60.65 = amountAfterCredit : 61.66 expected [61.66] but found [60.65]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [39] but found [21],
Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
AmountBeforeCredit: 60.65 = amountAfterCredit : 61.66 expected [61.66] but found [60.65]
at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount(IqSoft_API_4_Credit_Negative_Test.java:280)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- CreditAPIValidateResponseWithInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseWithInvalidToken" time="1.375">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [22] but found [0],
	Error Description:  expected [error login] but found [],
	amountAfterCredit = amountAfterDebit60.66 != 65.66 expected [65.66] but found [60.66]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [22] but found [0],
Error Description:  expected [error login] but found [],
amountAfterCredit = amountAfterDebit60.66 != 65.66 expected [65.66] but found [60.66]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseWithInvalidToken(IqSoft_API_5_Debit_Negative_Test.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseWithInvalidToken -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidProductID" time="1.44">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [43] but found [0],
	Error Description:  expected [game not available] but found [],
	amountAfterCredit = amountAfterDebit 64.66  =  69.66 expected [69.66] but found [64.66]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [43] but found [0],
Error Description:  expected [game not available] but found [],
amountAfterCredit = amountAfterDebit 64.66  =  69.66 expected [69.66] but found [64.66]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidProductID(IqSoft_API_5_Debit_Negative_Test.java:120)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidProductID -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingTransactionIDTwice" time="2.661">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [0] but found [21],
	Error Description: Transaction is already processed expected [null] but found [Transaction is already processed]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [0] but found [21],
Error Description: Transaction is already processed expected [null] but found [Transaction is already processed]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingTransactionIDTwice(IqSoft_API_5_Debit_Negative_Test.java:192)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingTransactionIDTwice -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidCreditTransactionID" time="0.821">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 0 expected [50] but found [0],
	Error Description:  expected [CanNotConnectCreditAndDebit] but found [],
	amountAfterDebit: 77.66 = amountBeforeDebit: 72.66 expected [72.66] but found [77.66]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 0 expected [50] but found [0],
Error Description:  expected [CanNotConnectCreditAndDebit] but found [],
amountAfterDebit: 77.66 = amountBeforeDebit: 72.66 expected [72.66] but found [77.66]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidCreditTransactionID(IqSoft_API_5_Debit_Negative_Test.java:230)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidCreditTransactionID -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="1.404">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [39] but found [21],
	Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
	expected [75.66] but found [76.66]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [39] but found [21],
Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
expected [75.66] but found [76.66]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidAmount(IqSoft_API_5_Debit_Negative_Test.java:279)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="1.455">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [39] but found [21],
	Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
	expected [73.16] but found [74.66]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [39] but found [21],
Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
expected [73.16] but found [74.66]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidAmount(IqSoft_API_5_Debit_Negative_Test.java:279)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="2.717">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [39] but found [21],
	Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
	expected [71.11] but found [72.16]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [39] but found [21],
Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
expected [71.11] but found [72.16]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidAmount(IqSoft_API_5_Debit_Negative_Test.java:279)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_5_Debit_Negative_Test" name="DebitAPIValidateResponseUsingInvalidAmount" time="2.269">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ResponseCode: 21 expected [39] but found [21],
	Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
	expected [69.11] but found [70.11]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
ResponseCode: 21 expected [39] but found [21],
Error Description: Invalid request params expected [WrongOperationAmount] but found [Invalid request params],
expected [69.11] but found [70.11]
at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidAmount(IqSoft_API_5_Debit_Negative_Test.java:279)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- DebitAPIValidateResponseUsingInvalidAmount -->
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseWithInvalidToken" time="1.404"/>
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingInvalidProductID" time="1.398"/>
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingSameTransactionIDForRollBackAndCredit" time="0.827"/>
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice" time="2.007">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	amountAfterRollBack1: 66.11 = amountBeforeCredit : 67.11 expected [67.11] but found [66.11]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
amountAfterRollBack1: 66.11 = amountBeforeCredit : 67.11 expected [67.11] but found [66.11]
at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice(IqSoft_API_6_RollBack_Negative_Test.java:218)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice -->
  <testcase classname="testCases.IqSoft_API_6_RollBack_Negative_Test" name="RollBackAPIValidateResponseUsingSameRollBackTransactionIDTwice" time="2.606">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	amountAfterRollBack1: 64.11 = amountAfterCredit2 : 64.11 + betAmountCreditConfig : 1.0 expected [65.11] but found [64.11]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
amountAfterRollBack1: 64.11 = amountAfterCredit2 : 64.11 + betAmountCreditConfig : 1.0 expected [65.11] but found [64.11]
at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseUsingSameRollBackTransactionIDTwice(IqSoft_API_6_RollBack_Negative_Test.java:292)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RollBackAPIValidateResponseUsingSameRollBackTransactionIDTwice -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite tearDownSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDownSuite -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setupSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setupSuite -->
</testsuite> <!-- API Integration Automation Test -->
