{"uuid":"17b1e309-0d4b-41fc-958a-42cd7d13e530","historyId":"f3ff1f99343980b749bef3f219dd9ece","fullName":"testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount","labels":[{"name":"package","value":"testCases.IqSoft_API_4_Credit_Negative_Test"},{"name":"testClass","value":"testCases.IqSoft_API_4_Credit_Negative_Test"},{"name":"testMethod","value":"CreditAPIValidateResponseWithInvalidAmount"},{"name":"parentSuite","value":"IQsoft API Integration"},{"name":"suite","value":"API Integration Automation Test"},{"name":"subSuite","value":"testCases.IqSoft_API_4_Credit_Negative_Test"},{"name":"host","value":"DESKTOP-PO3T4V3"},{"name":"thread","value":"16640@DESKTOP-PO3T4V3.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"severity","value":"blocker"}],"links":[],"name":"CreditAPIValidateResponseWithInvalidAmount","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"The following asserts failed:\n\tResponseCode: 0 expected [39] but found [0],\n\tError Description: null expected [WrongOperationAmount] but found [null]","trace":"java.lang.AssertionError: The following asserts failed:\n\tResponseCode: 0 expected [39] but found [0],\n\tError Description: null expected [WrongOperationAmount] but found [null]\r\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)\r\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)\r\n\tat testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount(IqSoft_API_4_Credit_Negative_Test.java:281)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:806)\r\n\tat org.testng.TestRunner.run(TestRunner.java:601)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:433)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\r\n\tat org.testng.TestNG.run(TestNG.java:1067)\r\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)\r\n\tat org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)\r\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)\r\n"},"stage":"finished","description":"Verify Credit API_s response with invalid Amount","steps":[],"attachments":[{"name":"GetBalanceAPI:  Url:  https://iqs.dazzabet.com/api/endpoint/GetBalance        RequestBody","source":"6d6ec4cd-dbde-42df-a5a2-e1c82a5b65f1-attachment.txt","type":"text/plain"},{"name":"GetBalanceAPI:  ResponseBody","source":"c97b724f-26f3-4f64-9aef-de7984aafa25-attachment.txt","type":"text/plain"},{"name":"CreditAPI  Url:  https://iqs.dazzabet.com/api/endpoint/Credit        RequestBody","source":"aa47e716-5b10-454e-923a-adc67384b129-attachment.txt","type":"text/plain"},{"name":"CreditAPI  ResponseBody","source":"d8c5c72f-72c7-48a2-9543-2436d659d777-attachment.txt","type":"text/plain"},{"name":"GetBalanceAPI:  Url:  https://iqs.dazzabet.com/api/endpoint/GetBalance        RequestBody","source":"68c8f60a-eaeb-4d42-823b-9c25e7b881c1-attachment.txt","type":"text/plain"},{"name":"GetBalanceAPI:  ResponseBody","source":"09bf13d1-e94e-4a97-b8d6-88b7815de2a7-attachment.txt","type":"text/plain"}],"parameters":[{"name":"arg0","value":"0.0"}],"start":1665737861324,"stop":1665737863037}