{"uuid":"5a925f1f-e4a1-4b61-bd74-52c7f2a98108","historyId":"f3ff1f99343980b749bef3f219dd9ece","fullName":"testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount","labels":[{"name":"package","value":"testCases.IqSoft_API_4_Credit_Negative_Test"},{"name":"testClass","value":"testCases.IqSoft_API_4_Credit_Negative_Test"},{"name":"testMethod","value":"CreditAPIValidateResponseWithInvalidAmount"},{"name":"parentSuite","value":"IQsoft API Integration"},{"name":"suite","value":"API Integration Automation Test"},{"name":"subSuite","value":"testCases.IqSoft_API_4_Credit_Negative_Test"},{"name":"host","value":"DESKTOP-PO3T4V3"},{"name":"thread","value":"3312@DESKTOP-PO3T4V3.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"severity","value":"blocker"}],"links":[],"name":"CreditAPIValidateResponseWithInvalidAmount","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"The following asserts failed:\n\tResponseCode: 0 expected [39] but found [0],\n\tError Description: null expected [WrongOperationAmount] but found [null]","trace":"java.lang.AssertionError: The following asserts failed:\n\tResponseCode: 0 expected [39] but found [0],\n\tError Description: null expected [WrongOperationAmount] but found [null]\r\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)\r\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)\r\n\tat testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount(IqSoft_API_4_Credit_Negative_Test.java:302)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:806)\r\n\tat org.testng.TestRunner.run(TestRunner.java:601)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:433)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\r\n\tat org.testng.TestNG.run(TestNG.java:1067)\r\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)\r\n\tat org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)\r\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)\r\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)\r\n"},"stage":"finished","description":"Verify Credit API_s response with invalid Amount","steps":[],"attachments":[{"name":"GetBalanceAPI RequestBody","source":"64bbbcc3-f03a-4684-a14e-280c6e7ffefd-attachment.txt","type":"text/plain"},{"name":"GetBalanceAPI ResponseBody","source":"cbb57f04-48f7-46db-9214-e77910015463-attachment.txt","type":"text/plain"},{"name":"CreditAPI RequestBody","source":"1308c333-8c04-46aa-98e2-73a1b39255a1-attachment.txt","type":"text/plain"},{"name":"CreditAPI ResponseBody","source":"c487b2e5-d39a-41f9-a385-f0d25b911fa9-attachment.txt","type":"text/plain"},{"name":"GetBalanceAPI RequestBody","source":"5a0d08f7-9b59-4b4a-b2f4-1cfa41644a2d-attachment.txt","type":"text/plain"},{"name":"GetBalanceAPI ResponseBody","source":"8388924e-e16a-43e7-9884-7017116f8092-attachment.txt","type":"text/plain"}],"parameters":[{"name":"arg0","value":"0.0"}],"start":1665488794888,"stop":1665488795432}