<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TestSuite" time="17.326" tests="55" errors="0" skipped="0" failures="19">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="java.vm.version" value="17.0.2+8-LTS-86"/>
    <property name="sun.boot.library.path" value="C:\Program Files\Java\jdk-17.0.2\bin"/>
    <property name="maven.multiModuleProjectDirectory" value="C:\Users\Nerses Khachatryan\Desktop\IQsoft_API_Integration-OpenGame\IQsoft_API_Integration-OpenGame\IQSoftAPI_Integration_QA"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="https://java.oracle.com/"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="path.separator" value=";"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="sun.os.patch.level" value=""/>
    <property name="user.script" value=""/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="C:\Users\Nerses Khachatryan\Desktop\IQsoft_API_Integration-OpenGame\IQsoft_API_Integration-OpenGame\IQSoftAPI_Integration_QA"/>
    <property name="java.vm.compressedOopsMode" value="32-bit"/>
    <property name="java.runtime.version" value="17.0.2+8-LTS-86"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="C:\Users\NERSES~1\AppData\Local\Temp\"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="user.variant" value=""/>
    <property name="os.name" value="Windows 10"/>
    <property name="classworlds.conf" value="C:\apache-maven-3.8.6-bin\apache-maven-3.8.6\bin\m2.conf"/>
    <property name="sun.jnu.encoding" value="Cp1252"/>
    <property name="java.library.path" value="C:\Program Files\Java\jdk-17.0.2\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Seq\;C:\Program Files\Seq\Client\;C:\Program Files\Java\jdk-17.0.2\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\nodejs\;C:\apache-maven-3.8.6-bin\apache-maven-3.8.6\bin;C:\apache-maven-3.8.6-bin\apache-maven-3.8.6;%M2_HOME%\bin;C:\Program Files\Git\cmd;C:\Users\Nerses Khachatryan\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\Nerses Khachatryan\AppData\Local\Programs\Python\Python310\;C:\Users\Nerses Khachatryan\AppData\Local\Microsoft\WindowsApps;C:\Users\Nerses Khachatryan\AppData\Roaming\npm;."/>
    <property name="maven.conf" value="C:\apache-maven-3.8.6-bin\apache-maven-3.8.6/conf"/>
    <property name="jdk.debug" value="release"/>
    <property name="java.class.version" value="61.0"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="10.0"/>
    <property name="library.jansi.path" value="C:\apache-maven-3.8.6-bin\apache-maven-3.8.6\lib\jansi-native"/>
    <property name="user.home" value="C:\Users\Nerses Khachatryan"/>
    <property name="user.timezone" value="Asia/Yerevan"/>
    <property name="file.encoding" value="Cp1252"/>
    <property name="java.specification.version" value="17"/>
    <property name="user.name" value="Nerses Khachatryan"/>
    <property name="java.class.path" value="C:\apache-maven-3.8.6-bin\apache-maven-3.8.6\boot\plexus-classworlds-2.6.0.jar"/>
    <property name="java.vm.specification.version" value="17"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher clean install"/>
    <property name="java.home" value="C:\Program Files\Java\jdk-17.0.2"/>
    <property name="user.language" value="en"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="java.vm.info" value="mixed mode, sharing"/>
    <property name="java.version" value="17.0.2"/>
    <property name="native.encoding" value="Cp1252"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="sun.stderr.encoding" value="cp437"/>
    <property name="maven.home" value="C:\apache-maven-3.8.6-bin\apache-maven-3.8.6"/>
    <property name="file.separator" value="\"/>
    <property name="java.version.date" value="2022-01-18"/>
    <property name="java.vendor.url.bug" value="https://bugreport.java.com/bugreport/"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.stdout.encoding" value="cp437"/>
    <property name="sun.cpu.isalist" value="amd64"/>
  </properties>
  <testcase name="openGameAPIValidateStatusCod" classname="testCases.IqSoft_API_1_OpenGame_Positive_Test" time="0.091"/>
  <testcase name="openGameAPIValidatePositiveResponse" classname="testCases.IqSoft_API_1_OpenGame_Positive_Test" time="0.023">
    <failure message="The following asserts failed:&#10;	ResponseCode: 21 expected [0] but found [21],&#10;	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [null] but found [An error occurred while updating the entries. See the inner exception for details.],&#10;	ResponseObject: null did not expect [null] but found [null],&#10;	ResponseObject Don&apos;t Contain http:// expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	ResponseCode: 21 expected [0] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [null] but found [An error occurred while updating the entries. See the inner exception for details.],
	ResponseObject: null did not expect [null] but found [null],
	ResponseObject Don't Contain http:// expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_1_OpenGame_Positive_Test.openGameAPIValidatePositiveResponse(IqSoft_API_1_OpenGame_Positive_Test.java:63)
</failure>
    <system-out><![CDATA[ERROR [main] (ReportingAllure.java:61)- openGameAPIValidatePositiveResponse Test failed
]]></system-out>
  </testcase>
  <testcase name="openGameAPIValidateResponseWithInvalidToken" classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" time="0.274"/>
  <testcase name="openGameAPIValidateResponseWithExpiredToken" classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" time="0.293">
    <failure message="The following asserts failed:&#10;	ResponseCode: 21 expected [22] but found [21],&#10;	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [Client not found] but found [An error occurred while updating the entries. See the inner exception for details.]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	ResponseCode: 21 expected [22] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [Client not found] but found [An error occurred while updating the entries. See the inner exception for details.]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_1_OpenGame_Negative_Test.openGameAPIValidateResponseWithExpiredToken(IqSoft_API_1_OpenGame_Negative_Test.java:81)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:102)- getURLRequestBody :{"PartnerId":61,"GameId":54351,"Token":"6cf0a441-455a-11ed-b772-ecb1d7ae60a8","LanguageId":"en","IsForMobile":false,"Domain":"dazarbet.com"}
 INFO [main] (IqSoft_API_1_OpenGame_Negative_Test.java:65)- OpenGame API ResponseCode is Equal: 21
 INFO [main] (IqSoft_API_1_OpenGame_Negative_Test.java:68)- OpenGame API Description is Equal: An error occurred while updating the entries. See the inner exception for details.
 INFO [main] (IqSoft_API_1_OpenGame_Negative_Test.java:71)- OpenGame API ResponseObject is Equal: null
 INFO [main] (IqSoft_API_1_OpenGame_Negative_Test.java:73)- OpenGame API Response Status Cod is Equal: 200
ERROR [main] (ReportingAllure.java:61)- openGameAPIValidateResponseWithExpiredToken Test failed
]]></system-out>
  </testcase>
  <testcase name="openGameAPIValidateResponseWithInvalidPartnerID" classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" time="0.348">
    <failure message="The following asserts failed:&#10;	ResponseCode 21 expected [22] but found [21],&#10;	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ClientNotFound ] but found [An error occurred while updating the entries. See the inner exception for details.]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	ResponseCode 21 expected [22] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ClientNotFound ] but found [An error occurred while updating the entries. See the inner exception for details.]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_1_OpenGame_Negative_Test.openGameAPIValidateResponseWithInvalidPartnerID(IqSoft_API_1_OpenGame_Negative_Test.java:114)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:102)- getURLRequestBody :{"PartnerId":-1,"GameId":54351,"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","LanguageId":"en","IsForMobile":false,"Domain":"dazarbet.com"}
 INFO [main] (IqSoft_API_1_OpenGame_Negative_Test.java:97)- OpenGame API ResponseCode is Equal: 21
 INFO [main] (IqSoft_API_1_OpenGame_Negative_Test.java:100)- OpenGame API Description is Equal: An error occurred while updating the entries. See the inner exception for details.
 INFO [main] (IqSoft_API_1_OpenGame_Negative_Test.java:103)- OpenGame API ResponseObject is Equal: null
 INFO [main] (IqSoft_API_1_OpenGame_Negative_Test.java:106)- OpenGame API Response Status Cod is Equal: 200
ERROR [main] (ReportingAllure.java:61)- openGameAPIValidateResponseWithInvalidPartnerID Test failed
]]></system-out>
  </testcase>
  <testcase name="openGameAPIValidateResponseWithInvalidGameID" classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" time="0.172"/>
  <testcase name="openGameAPIValidateResponseWithInvalidDomain" classname="testCases.IqSoft_API_1_OpenGame_Negative_Test" time="0.369">
    <failure message="The following asserts failed:&#10;	ResponseCode: 21 expected [43] but found [21],&#10;	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ProductNotFound] but found [An error occurred while updating the entries. See the inner exception for details.]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	ResponseCode: 21 expected [43] but found [21],
	Error Description: An error occurred while updating the entries. See the inner exception for details. expected [ProductNotFound] but found [An error occurred while updating the entries. See the inner exception for details.]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_1_OpenGame_Negative_Test.openGameAPIValidateResponseWithInvalidDomain(IqSoft_API_1_OpenGame_Negative_Test.java:179)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:102)- getURLRequestBody :{"PartnerId":61,"GameId":54351,"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","LanguageId":"en","IsForMobile":false,"Domain":"dazarbet.com1"}
 INFO [main] (IqSoft_API_1_OpenGame_Negative_Test.java:163)- OpenGame API ResponseCode is Equal: 21
 INFO [main] (IqSoft_API_1_OpenGame_Negative_Test.java:166)- OpenGame API Description is Equal: An error occurred while updating the entries. See the inner exception for details.
 INFO [main] (IqSoft_API_1_OpenGame_Negative_Test.java:169)- OpenGame API ResponseObject is Equal: null
 INFO [main] (IqSoft_API_1_OpenGame_Negative_Test.java:171)- OpenGame API Response Status Cod is Equal: 200
ERROR [main] (ReportingAllure.java:61)- openGameAPIValidateResponseWithInvalidDomain Test failed
]]></system-out>
  </testcase>
  <testcase name="AuthorizationAPIValidateStatusCod" classname="testCases.IqSoft_API_2_Authorization_Positive_Test" time="0.001"/>
  <testcase name="AuthorizationAPIValidatePositiveResponse" classname="testCases.IqSoft_API_2_Authorization_Positive_Test" time="0.001"/>
  <testcase name="GetBalanceAPIValidateStatusCod" classname="testCases.IqSoft_API_3_GetBalance_Positive_Test" time="0.004"/>
  <testcase name="GetBalanceAPIValidatePositiveResponse" classname="testCases.IqSoft_API_3_GetBalance_Positive_Test" time="0.008"/>
  <testcase name="CreditAPIValidateStatusCod" classname="testCases.IqSoft_API_4_Credit_Positive_Test" time="0.004"/>
  <testcase name="CreditAPIValidatePositiveResponse" classname="testCases.IqSoft_API_4_Credit_Positive_Test" time="0.004"/>
  <testcase name="DebitAPIValidateStatusCod" classname="testCases.IqSoft_API_5_Debit_Positive_Test" time="0.005"/>
  <testcase name="DebitAPIValidatePositiveResponse" classname="testCases.IqSoft_API_5_Debit_Positive_Test" time="0.007"/>
  <testcase name="RollBackAPIValidateStatusCod" classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" time="0.021"/>
  <testcase name="RollBackAPIValidatePositiveResponse" classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" time="0.003"/>
  <testcase name="RollBackAPIValidatePositiveResponseBalanceCorrection" classname="testCases.IqSoft_API_6_RollBackCreditWithDebit_Positive_Test" time="0.004"/>
  <testcase name="RollBackAPIValidateStatusCod" classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" time="0.01"/>
  <testcase name="RollBackAPIValidatePositiveResponse" classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" time="0"/>
  <testcase name="RollBackAPIValidatePositiveResponseBalanceCorrection" classname="testCases.IqSoft_API_6_RollBackCreditWithoutDebit_Positive_Test" time="0.002"/>
  <testcase name="RollBackAPIValidateStatusCod" classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" time="0.009"/>
  <testcase name="RollBackAPIValidatePositiveResponse" classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" time="0.001"/>
  <testcase name="RollBackAPIValidatePositiveResponseBalanceCorrection" classname="testCases.IqSoft_API_6_RollBackDebit_Positive_Test" time="0.002"/>
  <testcase name="AuthorizationAPIValidateResponseWithExpiredToken" classname="testCases.IqSoft_API_2_Authorization_Negative_Test" time="0.2">
    <failure message="The following asserts failed:&#10;	ResponseCode: 0 expected [29] but found [0],&#10;	Error Description: null expected [SessionExpired] but found [null]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	ResponseCode: 0 expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_2_Authorization_Negative_Test.AuthorizationAPIValidateResponseWithExpiredToken(IqSoft_API_2_Authorization_Negative_Test.java:48)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:117)- AuthorizationRequestBody : {"Token":"6cf0a441-455a-11ed-b772-ecb1d7ae60a8","ProductId":54351}
 INFO [main] (IqSoft_API_2_Authorization_Negative_Test.java:30)- Authorization API Response Status cod : 200
 INFO [main] (IqSoft_API_2_Authorization_Negative_Test.java:35)- Authorization API Response ResponseCode : 0
 INFO [main] (IqSoft_API_2_Authorization_Negative_Test.java:38)- Authorization API Response Description : null
ERROR [main] (ReportingAllure.java:61)- AuthorizationAPIValidateResponseWithExpiredToken Test failed
]]></system-out>
  </testcase>
  <testcase name="AuthorizationAPIValidateResponseWithInvalidToken" classname="testCases.IqSoft_API_2_Authorization_Negative_Test" time="0.176"/>
  <testcase name="AuthorizationAPIValidateResponseWithInvalidProductID" classname="testCases.IqSoft_API_2_Authorization_Negative_Test" time="0.184">
    <failure message="The following asserts failed:&#10;	ResponseCode: 0 expected [43] but found [0],&#10;	Error Description: null expected [ProductNotFound] but found [null]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	ResponseCode: 0 expected [43] but found [0],
	Error Description: null expected [ProductNotFound] but found [null]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_2_Authorization_Negative_Test.AuthorizationAPIValidateResponseWithInvalidProductID(IqSoft_API_2_Authorization_Negative_Test.java:109)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:117)- AuthorizationRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","ProductId":54351}
 INFO [main] (IqSoft_API_2_Authorization_Negative_Test.java:92)- Authorization API Response Status cod : 200
 INFO [main] (IqSoft_API_2_Authorization_Negative_Test.java:97)- Authorization API Response ResponseCode : 0
 INFO [main] (IqSoft_API_2_Authorization_Negative_Test.java:100)- Authorization API Response Description : null
ERROR [main] (ReportingAllure.java:61)- AuthorizationAPIValidateResponseWithInvalidProductID Test failed
]]></system-out>
  </testcase>
  <testcase name="GetBalanceAPIValidateResponseWithExpiredToken" classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" time="0.18">
    <failure message="The following asserts failed:&#10;	ResponseCode: 0 expected [29] but found [0],&#10;	Error Description: null expected [SessionExpired] but found [null]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	ResponseCode: 0 expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithExpiredToken(IqSoft_API_3_GetBalance_Negative_Test.java:43)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"6cf0a441-455a-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (IqSoft_API_3_GetBalance_Negative_Test.java:30)- GetBalance API Response ResponseCode : 0
 INFO [main] (IqSoft_API_3_GetBalance_Negative_Test.java:33)- GetBalance API Response Description : null
ERROR [main] (ReportingAllure.java:61)- GetBalanceAPIValidateResponseWithExpiredToken Test failed
]]></system-out>
  </testcase>
  <testcase name="GetBalanceAPIValidateResponseWithInvalidToken" classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" time="0.188"/>
  <testcase name="GetBalanceAPIValidateResponseWithInvalidCurrencyID" classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" time="0.205">
    <failure message="The following asserts failed:&#10;	ResponseCode: 0 expected [20] but found [0],&#10;	Error Description: null expected [CurrencyNotExists] but found [null]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	ResponseCode: 0 expected [20] but found [0],
	Error Description: null expected [CurrencyNotExists] but found [null]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithInvalidCurrencyID(IqSoft_API_3_GetBalance_Negative_Test.java:98)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND1"}
 INFO [main] (IqSoft_API_3_GetBalance_Negative_Test.java:84)- GetBalance API Response ResponseCode : 0
 INFO [main] (IqSoft_API_3_GetBalance_Negative_Test.java:87)- GetBalance API Response Description : null
ERROR [main] (ReportingAllure.java:61)- GetBalanceAPIValidateResponseWithInvalidCurrencyID Test failed
]]></system-out>
  </testcase>
  <testcase name="GetBalanceAPIValidateResponseWithOtherCurrencyID" classname="testCases.IqSoft_API_3_GetBalance_Negative_Test" time="0.373">
    <failure message="balanceUSD VS balanceEUR did not expect [9794.0] but found [9794.0]" type="java.lang.AssertionError">java.lang.AssertionError: balanceUSD VS balanceEUR did not expect [9794.0] but found [9794.0]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failEquals(Assert.java:1417)
	at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
	at org.testng.Assert.assertNotEquals(Assert.java:2033)
	at testCases.IqSoft_API_3_GetBalance_Negative_Test.GetBalanceAPIValidateResponseWithOtherCurrencyID(IqSoft_API_3_GetBalance_Negative_Test.java:121)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"USD"}
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"EUR"}
ERROR [main] (ReportingAllure.java:61)- GetBalanceAPIValidateResponseWithOtherCurrencyID Test failed
]]></system-out>
  </testcase>
  <testcase name="CreditAPIValidateResponseWithExpiredToken" classname="testCases.IqSoft_API_4_Credit_Negative_Test" time="0.542">
    <failure message="The following asserts failed:&#10;	ResponseCode: 0 expected [29] but found [0],&#10;	Error Description: null expected [SessionExpired] but found [null],&#10;	amountBeforeCredit = amountAfterCredit: 9794.0 = 9793.0 expected [9793.0] but found [9794.0]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	ResponseCode: 0 expected [29] but found [0],
	Error Description: null expected [SessionExpired] but found [null],
	amountBeforeCredit = amountAfterCredit: 9794.0 = 9793.0 expected [9793.0] but found [9794.0]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithExpiredToken(IqSoft_API_4_Credit_Negative_Test.java:63)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (BaseTest.java:162)- CreditRequestBody : {"Token":"6cf0a441-455a-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND","GameId":54351,"OperationTypeId":1,"TransactionId":"QA_Test-f9qBeM4KpYvMbfVeV34q_C","BetState":1,"Amount":1.0}
 INFO [main] (IqSoft_API_4_Credit_Negative_Test.java:43)- Credit API Response ResponseCode : 0
 INFO [main] (IqSoft_API_4_Credit_Negative_Test.java:46)- Credit API Response Description : null
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
ERROR [main] (ReportingAllure.java:61)- CreditAPIValidateResponseWithExpiredToken Test failed
]]></system-out>
  </testcase>
  <testcase name="CreditAPIValidateResponseWithInvalidToken" classname="testCases.IqSoft_API_4_Credit_Negative_Test" time="0.557"/>
  <testcase name="CreditAPIValidateResponseWithInvalidProductID" classname="testCases.IqSoft_API_4_Credit_Negative_Test" time="0.552">
    <failure message="The following asserts failed:&#10;	Error Description: game not avaible expected [game not available] but found [game not avaible]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	Error Description: game not avaible expected [game not available] but found [game not avaible]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidProductID(IqSoft_API_4_Credit_Negative_Test.java:153)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (BaseTest.java:162)- CreditRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND","GameId":-10,"OperationTypeId":1,"TransactionId":"QA_Test-KMgL5WzEM1x1jcxMj1UL_C","BetState":1,"Amount":1.0}
 INFO [main] (IqSoft_API_4_Credit_Negative_Test.java:132)- Credit API Response ResponseCode : 43
 INFO [main] (IqSoft_API_4_Credit_Negative_Test.java:135)- Credit API Response Description : game not avaible
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
ERROR [main] (ReportingAllure.java:61)- CreditAPIValidateResponseWithInvalidProductID Test failed
]]></system-out>
  </testcase>
  <testcase name="CreditAPIValidateResponseUsingTransactionIDTwice" classname="testCases.IqSoft_API_4_Credit_Negative_Test" time="0.92"/>
  <testcase name="CreditAPIValidateResponseUsingAmountHigherThenBalance" classname="testCases.IqSoft_API_4_Credit_Negative_Test" time="0.552"/>
  <testcase name="CreditAPIValidateResponseWithInvalidAmount" classname="testCases.IqSoft_API_4_Credit_Negative_Test" time="0.553">
    <failure message="The following asserts failed:&#10;	ResponseCode: 0 expected [39] but found [0],&#10;	Error Description: null expected [WrongOperationAmount] but found [null]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	ResponseCode: 0 expected [39] but found [0],
	Error Description: null expected [WrongOperationAmount] but found [null]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_4_Credit_Negative_Test.CreditAPIValidateResponseWithInvalidAmount(IqSoft_API_4_Credit_Negative_Test.java:302)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (BaseTest.java:162)- CreditRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND","GameId":54351,"OperationTypeId":1,"TransactionId":"QA_Test-IM94sL3K4LatPPuRBsED_C","BetState":1,"Amount":0.0}
 INFO [main] (IqSoft_API_4_Credit_Negative_Test.java:281)- Credit API Response ResponseCode : 0
 INFO [main] (IqSoft_API_4_Credit_Negative_Test.java:284)- Credit API Response Description : null
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
ERROR [main] (ReportingAllure.java:61)- CreditAPIValidateResponseWithInvalidAmount Test failed
]]></system-out>
  </testcase>
  <testcase name="CreditAPIValidateResponseWithInvalidAmount" classname="testCases.IqSoft_API_4_Credit_Negative_Test" time="0.546"/>
  <testcase name="CreditAPIValidateResponseWithInvalidAmount" classname="testCases.IqSoft_API_4_Credit_Negative_Test" time="0.563"/>
  <testcase name="CreditAPIValidateResponseWithInvalidAmount" classname="testCases.IqSoft_API_4_Credit_Negative_Test" time="0.554"/>
  <testcase name="CreditAPIValidateResponseWithInvalidAmount" classname="testCases.IqSoft_API_4_Credit_Negative_Test" time="0.571"/>
  <testcase name="DebitAPIValidateResponseWithInvalidToken" classname="testCases.IqSoft_API_5_Debit_Negative_Test" time="0.917"/>
  <testcase name="DebitAPIValidateResponseUsingInvalidProductID" classname="testCases.IqSoft_API_5_Debit_Negative_Test" time="0.931">
    <failure message="The following asserts failed:&#10;	Error Description: game not avaible expected [game not available] but found [game not avaible]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	Error Description: game not avaible expected [game not available] but found [game not avaible]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidProductID(IqSoft_API_5_Debit_Negative_Test.java:126)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (BaseTest.java:162)- CreditRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND","GameId":54351,"OperationTypeId":1,"TransactionId":"QA_Test-CjpBhSI2xCcyP3r2ir0D_C","BetState":1,"Amount":1.0}
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (BaseTest.java:190)- DebitRequestBody : {"ClientId":"dazzabet10130","CurrencyId":"TND","GameId":-10,"TransactionId":"QA_Test-P0gZYQP2x7CIPNJY3Joo_D","CreditTransactionId":"QA_Test-CjpBhSI2xCcyP3r2ir0D_C","Amount":2.0,"BetState":2,"OperationTypeId":4,"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8"}
 INFO [main] (IqSoft_API_5_Debit_Negative_Test.java:106)- Debit API Response ResponseCode : 43
 INFO [main] (IqSoft_API_5_Debit_Negative_Test.java:109)- Debit API Response Description : game not avaible
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
ERROR [main] (ReportingAllure.java:61)- DebitAPIValidateResponseUsingInvalidProductID Test failed
]]></system-out>
  </testcase>
  <testcase name="DebitAPIValidateResponseUsingTransactionIDTwice" classname="testCases.IqSoft_API_5_Debit_Negative_Test" time="1.703">
    <failure message="The following asserts failed:&#10;	ResponseCode: 0 expected [69] but found [0],&#10;	Error Description: null expected [ClientDocumentAlreadyExists] but found [null]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	ResponseCode: 0 expected [69] but found [0],
	Error Description: null expected [ClientDocumentAlreadyExists] but found [null]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingTransactionIDTwice(IqSoft_API_5_Debit_Negative_Test.java:201)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (BaseTest.java:162)- CreditRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND","GameId":54351,"OperationTypeId":1,"TransactionId":"QA_Test-gkAKelEdutCr040dfB1W_C","BetState":1,"Amount":1.0}
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (BaseTest.java:162)- CreditRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND","GameId":54351,"OperationTypeId":1,"TransactionId":"QA_Test-j1bLA7firvvp8qu8hXPB_C","BetState":1,"Amount":1.0}
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (BaseTest.java:190)- DebitRequestBody : {"ClientId":"dazzabet10130","CurrencyId":"TND","GameId":54351,"TransactionId":"QA_Test-ls09jMozl6ioz40NA11w_D","CreditTransactionId":"QA_Test-gkAKelEdutCr040dfB1W_C","Amount":2.0,"BetState":2,"OperationTypeId":4,"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8"}
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (BaseTest.java:190)- DebitRequestBody : {"ClientId":"dazzabet10130","CurrencyId":"TND","GameId":54351,"TransactionId":"QA_Test-ls09jMozl6ioz40NA11w_D","CreditTransactionId":"QA_Test-j1bLA7firvvp8qu8hXPB_C","Amount":2.0,"BetState":2,"OperationTypeId":4,"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8"}
 INFO [main] (IqSoft_API_5_Debit_Negative_Test.java:180)- Debit API Response ResponseCode : 0
 INFO [main] (IqSoft_API_5_Debit_Negative_Test.java:183)- Debit API Response Description : null
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
ERROR [main] (ReportingAllure.java:61)- DebitAPIValidateResponseUsingTransactionIDTwice Test failed
]]></system-out>
  </testcase>
  <testcase name="DebitAPIValidateResponseUsingInvalidCreditTransactionID" classname="testCases.IqSoft_API_5_Debit_Negative_Test" time="0.558">
    <failure message="The following asserts failed:&#10;	ResponseCode: 0 expected [50] but found [0],&#10;	Error Description: null expected [CanNotConnectCreditAndDebit] but found [null],&#10;	amountBeforeDebit: 9790.0 = amountAfterDebit: 9792.0 expected [9792.0] but found [9790.0]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	ResponseCode: 0 expected [50] but found [0],
	Error Description: null expected [CanNotConnectCreditAndDebit] but found [null],
	amountBeforeDebit: 9790.0 = amountAfterDebit: 9792.0 expected [9792.0] but found [9790.0]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidCreditTransactionID(IqSoft_API_5_Debit_Negative_Test.java:242)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (BaseTest.java:190)- DebitRequestBody : {"ClientId":"dazzabet10130","CurrencyId":"TND","GameId":54351,"TransactionId":"QA_Test-IjeqKMXWwQSEtH9CPkn0_D","CreditTransactionId":"QA_Test-G1WLpGrGQPcXWMe9tOgh_C_ErrorID","Amount":2.0,"BetState":2,"OperationTypeId":4,"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8"}
 INFO [main] (IqSoft_API_5_Debit_Negative_Test.java:225)- Debit API Response ResponseCode : 0
 INFO [main] (IqSoft_API_5_Debit_Negative_Test.java:228)- Debit API Response Description : null
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
ERROR [main] (ReportingAllure.java:61)- DebitAPIValidateResponseUsingInvalidCreditTransactionID Test failed
]]></system-out>
  </testcase>
  <testcase name="DebitAPIValidateResponseUsingInvalidAmount" classname="testCases.IqSoft_API_5_Debit_Negative_Test" time="0.945">
    <failure message="The following asserts failed:&#10;	ResponseCode: 0 expected [39] but found [0],&#10;	Error Description: null expected [WrongOperationAmount] but found [null]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	ResponseCode: 0 expected [39] but found [0],
	Error Description: null expected [WrongOperationAmount] but found [null]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_5_Debit_Negative_Test.DebitAPIValidateResponseUsingInvalidAmount(IqSoft_API_5_Debit_Negative_Test.java:294)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (BaseTest.java:162)- CreditRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND","GameId":54351,"OperationTypeId":1,"TransactionId":"QA_Test-ujSvIQnokdtK40CH6NYr_C","BetState":1,"Amount":1.0}
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (BaseTest.java:190)- DebitRequestBody : {"ClientId":"dazzabet10130","CurrencyId":"TND","GameId":54351,"TransactionId":"QA_Test-oYIdp2Jhr25x7BBiJf88_D","CreditTransactionId":"QA_Test-ujSvIQnokdtK40CH6NYr_C","Amount":0.0,"BetState":2,"OperationTypeId":4,"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8"}
 INFO [main] (IqSoft_API_5_Debit_Negative_Test.java:276)- Debit API Response ResponseCode : 0
 INFO [main] (IqSoft_API_5_Debit_Negative_Test.java:279)- Debit API Response Description : null
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
ERROR [main] (ReportingAllure.java:61)- DebitAPIValidateResponseUsingInvalidAmount Test failed
]]></system-out>
  </testcase>
  <testcase name="DebitAPIValidateResponseUsingInvalidAmount" classname="testCases.IqSoft_API_5_Debit_Negative_Test" time="0.906"/>
  <testcase name="DebitAPIValidateResponseUsingInvalidAmount" classname="testCases.IqSoft_API_5_Debit_Negative_Test" time="0.924"/>
  <testcase name="DebitAPIValidateResponseUsingInvalidAmount" classname="testCases.IqSoft_API_5_Debit_Negative_Test" time="0.916"/>
  <testcase name="DebitAPIValidateResponseUsingInvalidAmount" classname="testCases.IqSoft_API_5_Debit_Negative_Test" time="0.96"/>
  <testcase name="RollBackAPIValidateResponseWithInvalidToken" classname="testCases.IqSoft_API_6_RollBack_Negative_Test" time="0.95">
    <failure message="The following asserts failed:&#10;	amountAfterCredit: 9786.0 = amountAfterRollBack : 9787.0 expected [9787.0] but found [9786.0]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	amountAfterCredit: 9786.0 = amountAfterRollBack : 9787.0 expected [9787.0] but found [9786.0]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseWithInvalidToken(IqSoft_API_6_RollBack_Negative_Test.java:70)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:32)- Balance Before Credit:9787.0
 INFO [main] (BaseTest.java:162)- CreditRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND","GameId":54351,"OperationTypeId":1,"TransactionId":"QA_Test-gKg8SEQxC7ijPaBhANy1_C","BetState":1,"Amount":1.0}
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:42)- Balance After Credit:9786.0
 INFO [main] (BaseTest.java:210)- RollBackRequestBody : {"UserName":"testuser","GameId":54351,"RollbackTransactionId":"QA_Test-gKg8SEQxC7ijPaBhANy1_C","TransactionId":"QA_Test-hgJNTaWj4xrUg5pDCQG8_R","OperationTypeId":4,"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8Error"}
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:51)- RollBack API Response ResponseCode : 0
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:54)- RollBack API Response Description : null
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:61)- Balance After RollBack:9787.0
ERROR [main] (ReportingAllure.java:61)- RollBackAPIValidateResponseWithInvalidToken Test failed
]]></system-out>
  </testcase>
  <testcase name="RollBackAPIValidateResponseUsingInvalidProductID" classname="testCases.IqSoft_API_6_RollBack_Negative_Test" time="0.919">
    <failure message="The following asserts failed:&#10;	amountAfterRollBack : 9787.0 = amountAfterCredit: 9786.0 expected [9786.0] but found [9787.0]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	amountAfterRollBack : 9787.0 = amountAfterCredit: 9786.0 expected [9786.0] but found [9787.0]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseUsingInvalidProductID(IqSoft_API_6_RollBack_Negative_Test.java:125)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:88)- Balance Before Credit:9787.0
 INFO [main] (BaseTest.java:162)- CreditRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND","GameId":54351,"OperationTypeId":1,"TransactionId":"QA_Test-zoI2VRUIRALG2PZVqTvG_C","BetState":1,"Amount":1.0}
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:98)- Balance After Credit:9786.0
 INFO [main] (BaseTest.java:210)- RollBackRequestBody : {"UserName":"testuser","GameId":-10,"RollbackTransactionId":"QA_Test-zoI2VRUIRALG2PZVqTvG_C","TransactionId":"QA_Test-4BPUnrJwYjLWmj5q5qfk_R","OperationTypeId":4,"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8"}
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:107)- RollBack API Response ResponseCode : 0
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:110)- RollBack API Response Description : null
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:117)- Balance After RollBack:9787.0
ERROR [main] (ReportingAllure.java:61)- RollBackAPIValidateResponseUsingInvalidProductID Test failed
]]></system-out>
  </testcase>
  <testcase name="RollBackAPIValidateResponseUsingSameTransactionIDForRollBackAndCredit" classname="testCases.IqSoft_API_6_RollBack_Negative_Test" time="0.568"/>
  <testcase name="RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice" classname="testCases.IqSoft_API_6_RollBack_Negative_Test" time="1.285">
    <failure message="The following asserts failed:&#10;	amountAfterRollBack1: 9787.0 = amountAfterRollBack2 : 9788.0 expected [9788.0] but found [9787.0]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	amountAfterRollBack1: 9787.0 = amountAfterRollBack2 : 9788.0 expected [9788.0] but found [9787.0]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
	at testCases.IqSoft_API_6_RollBack_Negative_Test.RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice(IqSoft_API_6_RollBack_Negative_Test.java:232)
</failure>
    <system-out><![CDATA[ INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:183)- Balance Before Credit:9787.0
 INFO [main] (BaseTest.java:162)- CreditRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND","GameId":54351,"OperationTypeId":1,"TransactionId":"QA_Test-zUAEyBWAERbtzCWmnkmP_C","BetState":1,"Amount":1.0}
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:193)- Balance After Credit:9786.0
 INFO [main] (BaseTest.java:210)- RollBackRequestBody : {"UserName":"testuser","GameId":54351,"RollbackTransactionId":"QA_Test-zUAEyBWAERbtzCWmnkmP_C","TransactionId":"QA_Test-Ltr5j8yK53QNojBFGxre_R","OperationTypeId":4,"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8"}
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:203)- Balance After RollBack:9787.0
 INFO [main] (BaseTest.java:210)- RollBackRequestBody : {"UserName":"testuser","GameId":54351,"RollbackTransactionId":"QA_Test-zUAEyBWAERbtzCWmnkmP_C","TransactionId":"QA_Test-7k2wgEerGzKU8dxtzU9r_R","OperationTypeId":4,"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8"}
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:212)- RollBack API Response ResponseCode : 0
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:215)- RollBack API Response Description : null
 INFO [main] (BaseTest.java:133)- GetBalanceRequestBody : {"Token":"e30214f9-4872-11ed-b772-ecb1d7ae60a8","CurrencyId":"TND"}
 INFO [main] (IqSoft_API_6_RollBack_Negative_Test.java:222)- Balance After RollBack:9788.0
ERROR [main] (ReportingAllure.java:61)- RollBackAPIValidateResponseUsingSameCreditTransactionIDTwice Test failed
]]></system-out>
  </testcase>
  <testcase name="RollBackAPIValidateResponseUsingSameRollBackTransactionIDTwice" classname="testCases.IqSoft_API_6_RollBack_Negative_Test" time="1.712"/>
</testsuite>